### ISSUE TITLE
Bitmap ICON palette glitch Ver. 1.1.1

### ISSUE THREAD

**Issue by TommyLaszlo** [inkyblackness/hacked#37]
![color_error_1](https://user-images.githubusercontent.com/42920964/44963201-992f4580-aef6-11e8-9b4f-ada85ff9eb15.JPG)

Whenever I go to import a PNG or a GIF into the ICON section I get this error. This error does not happen in Ver. 1.0.0, it is not just index 0, it is all of them.

![color_error_2](https://user-images.githubusercontent.com/42920964/44963223-dc89b400-aef6-11e8-9d43-432cea825f2d.JPG)

**Comment by dertseha** [comment]
Hello there and thank you for the message!

Image import has been extended:
* If it is a non-paletted one, then the colors are mapped to the game palette as good as possible (the known behaviour). With one change: To avoid setting one of the "animated" colors, these indices are ignored when mapping.
* If the image is a paletted one, then color indices are taken directly, ignoring the color value. The motivation here is to allow to work with the same palette, and provide a way how the image artist can still precisely set animated pixels.

I assume this is was happened to you - especially with .gif files - the images you took were paletted and their palette didn't match that of the game.

To get back to the "known" behaviour, save your images as non-paletted ones (e.g. true-color) and then import.
Would this work for you?

As an alternative I had the following idea: If the palette of the paletted image does not match exactly that of the game, then also perform the mapping like before.

Though, I'm also getting reports that, at least for texture import, the image is still messed up when following above rules. There might be another fix necessary :(

**Comment by TommyLaszlo** [comment]
Thank you so much! I just have a few questions regarding paletted images, I was reading around that the engine required images that were '_indexed 256 color 8bit images'_ so that's what I initially ended up testing, with the notice that some pixels were animated.

So would you suggest that I index the images as _24bit RGB PNGs_? Is that what you're refering to when you say _True-Color_?

Also is there a way to determine which pixels are considered animated, and is there a way to specifically _set them?_ 

Thanks again

**Comment by dertseha** [comment]
If you don't need these animated pixels, then can use a non-paletted image, such as 24bit ones. The editor will then try to match the colors in there as best as possible to the in-game palette.

In order to re-use the actual colors from the game, you'll need to work with its palette. You can obtain the palette by exporting one image and then reuse that palette.
Only when using this palette, you can make use of the animated palette colors. The list of looped indices is here: https://github.com/inkyblackness/ss-specs/blob/master/media/Palettes.md#pixel-animation--palette-looping 
If you set pixels to colors of these indices, they will be blinking.

**Comment by dertseha** [comment]
Special handling added. Paletted images are now taken literally *only* if the palette matches that of the game.
