### ISSUE TITLE
ss1/content/text: indexing after nil check without len check

### ISSUE THREAD

**Issue by Quasilyte** [inkyblackness/hacked#52]
I found suspicious conditional expression inside `ss1/content/text` package:

https://github.com/inkyblackness/hacked/blob/master/ss1/content/text/ElectronicMessage.go#L108

```go
if (metaData == nil) || (len(metaData[0]) != len(metaString)) {
		err = fmt.Errorf("failed to parse meta string: <%v>", metaString)
}
```

`metaData` checked for not being nil and then 1st element is accessed (index=0). But that nil check doesn't cover non-nil slice with a length of 0 (empty slice). Maybe `len(metaData) != 0` is more suitable there?

```diff
- if (metaData == nil) || (len(metaData[0]) != len(metaString)) {
+ if len(metaData) == 0 || (len(metaData[0]) != len(metaString)) {
```

Or is panic in a case of the empty slice is desirable there?

**Comment by dertseha** [comment]
Heh - after finally going over the code, I found it to be another case of "well, actually - the code is OK the way it is", yet it is far easier to make the code conform to a more common style rather than depend on some external specialities and have some opinionated argument. :) (I truly love linters ;) )

For reference: The value `metaData` is the result of (Regexp.FindStringSubmatch)[https://golang.org/pkg/regexp/#Regexp.FindStringSubmatch]. This function returns nil on no match, otherwise a slice of at least one entry (the matching text) - so _in this particular case_, it would have been fine. Hence removing the "bug" label.

thank you again!
